#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#

#
# Copyright 2019 Joyent, Inc.
#


PROGNAME = epoll_bofh
CFLAGS = -pthread -fno-omit-frame-pointer

all: $(PROGNAME)

clean:
	rm -f $(PROGNAME)

.PHONEY: clean
